### ISSUE TITLE
Deploy the service automatically to all compute options

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/multiple-deployment-options#1]
Aim is to provide a DevOps toolchain to automatically deploy the service as a Cloud Foundry app, in a Kubernetes cluster and as an OpenWhisk action.

**Comment by l2fprod** [comment]
@Twanawebtech 

I came across this: https://developer.ibm.com/recipes/tutorials/deploy-kubernetes-pods-to-the-bluemix-container-service-using-devops-pipelines/

and the source
https://github.com/IBMCloudDevOps/bluemix-kubernetes-sample

**Comment by Twanawebtech** [comment]
That's good, I am reviewing them.
