### ISSUE TITLE
Wait for the Kubernetes cluster creation in the toolchain

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/multiple-deployment-options#19]

**Comment by Twanawebtech** [comment]
This done, need to test this once the toolchain issue is resolved.

**Comment by Twanawebtech** [comment]
@l2fprod  we have to change the steps, it is not ideal at the moment to allow the Toolchain to create the cluster

Toolchain job times out after 60mins
and it takes longer then 60mins most of the time for a cluster to be created and be up

**Comment by Twanawebtech** [comment]
What are your thoughts?
 
<img width="959" alt="screenshot 2017-05-04 17 01 04" src="https://cloud.githubusercontent.com/assets/12715466/25713136/9d7a1e74-30eb-11e7-8edb-0a7bb27acb16.png">

**Comment by l2fprod** [comment]
Agreed. I'll do the required changes:
https://github.com/IBM-Bluemix/multiple-deployment-options/issues/27
